In [ ]:
from tensorflow.keras.preprocessing.text import  one_hot


In [3]:
#sentences

sentence = [
    'The cat sits on the mat',
    'She loves playing guitar',
    'He enjoys reading books',
    'The sun is shining bright',
    'Birds are flying in the sky',
    'I like to drink coffee',
    'They went to the park',
    'The dog barked loudly'
]

In [4]:
#define vocabulary size

voc_size = 10000


In [6]:
#One Hot representation for every word
one_hot_repr = [one_hot(words,voc_size) for words in sentence]

In [7]:
#word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [8]:
import numpy as np



In [22]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding="post",maxlen=sent_length)
print(embedded_docs)

[[6428 7718 3317 3843 6428 5560    0    0]
 [9561 3949 8779 9867    0    0    0    0]
 [ 750 2299 5955 4817    0    0    0    0]
 [6428 7810 2744 1926 9358    0    0    0]
 [ 185 6511 6897 2091 6428 5120    0    0]
 [8310 1472 5432 8469 4141    0    0    0]
 [2086  164 5432 6428 1877    0    0    0]
 [6428 6480 8229 2891    0    0    0    0]]


In [32]:
#feature representation
dim=10 #dim=dimension
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))

model.compile('adam','mse')


c:\Users\user\Desktop\yeni layiheler\generative AI lessons 2\projectml2\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [33]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step


array([[[ 0.0405187 , -0.02768498,  0.01004212,  0.02627001,
          0.02339132,  0.0008622 ,  0.04752331,  0.00222443,
          0.00015458, -0.01334288],
        [ 0.02370388, -0.02295922, -0.02538743,  0.0254712 ,
         -0.02547601,  0.00486822,  0.04235986,  0.03320752,
         -0.01949067, -0.00746859],
        [ 0.0248956 ,  0.00265752,  0.01881523,  0.00230174,
         -0.04280499, -0.00222052,  0.01278568, -0.04331669,
         -0.00547455,  0.00326081],
        [ 0.01812193, -0.00496901, -0.00194676, -0.04460622,
          0.00886082, -0.03964105, -0.03959868,  0.0447336 ,
          0.02116552, -0.04729748],
        [ 0.0405187 , -0.02768498,  0.01004212,  0.02627001,
          0.02339132,  0.0008622 ,  0.04752331,  0.00222443,
          0.00015458, -0.01334288],
        [-0.04758533, -0.01623269,  0.04581991, -0.02314019,
          0.01792936, -0.03788083,  0.00841209, -0.04059238,
         -0.03569251, -0.0216839 ],
        [-0.04469451,  0.03671138, -0.03796912,  0.0

In [40]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step


array([[[ 0.0405187 , -0.02768498,  0.01004212,  0.02627001,
          0.02339132,  0.0008622 ,  0.04752331,  0.00222443,
          0.00015458, -0.01334288],
        [ 0.02370388, -0.02295922, -0.02538743,  0.0254712 ,
         -0.02547601,  0.00486822,  0.04235986,  0.03320752,
         -0.01949067, -0.00746859],
        [ 0.0248956 ,  0.00265752,  0.01881523,  0.00230174,
         -0.04280499, -0.00222052,  0.01278568, -0.04331669,
         -0.00547455,  0.00326081],
        [ 0.01812193, -0.00496901, -0.00194676, -0.04460622,
          0.00886082, -0.03964105, -0.03959868,  0.0447336 ,
          0.02116552, -0.04729748],
        [ 0.0405187 , -0.02768498,  0.01004212,  0.02627001,
          0.02339132,  0.0008622 ,  0.04752331,  0.00222443,
          0.00015458, -0.01334288],
        [-0.04758533, -0.01623269,  0.04581991, -0.02314019,
          0.01792936, -0.03788083,  0.00841209, -0.04059238,
         -0.03569251, -0.0216839 ],
        [-0.04469451,  0.03671138, -0.03796912,  0.0

In [50]:
# model.predict(embedded_docs)
model.predict(np.expand_dims(embedded_docs[0],axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([[[ 0.0405187 , -0.02768498,  0.01004212,  0.02627001,
          0.02339132,  0.0008622 ,  0.04752331,  0.00222443,
          0.00015458, -0.01334288],
        [ 0.02370388, -0.02295922, -0.02538743,  0.0254712 ,
         -0.02547601,  0.00486822,  0.04235986,  0.03320752,
         -0.01949067, -0.00746859],
        [ 0.0248956 ,  0.00265752,  0.01881523,  0.00230174,
         -0.04280499, -0.00222052,  0.01278568, -0.04331669,
         -0.00547455,  0.00326081],
        [ 0.01812193, -0.00496901, -0.00194676, -0.04460622,
          0.00886082, -0.03964105, -0.03959868,  0.0447336 ,
          0.02116552, -0.04729748],
        [ 0.0405187 , -0.02768498,  0.01004212,  0.02627001,
          0.02339132,  0.0008622 ,  0.04752331,  0.00222443,
          0.00015458, -0.01334288],
        [-0.04758533, -0.01623269,  0.04581991, -0.02314019,
          0.01792936, -0.03788083,  0.00841209, -0.04059238,
         -0.03569251, -0.0216839 ],
        [-0.04469451,  0.03671138, -0.03796912,  0.0

In [53]:
arr = np.array([1, 2,3,4])

arr.shape

(4,)

In [55]:
arr_expanded = np.expand_dims(arr,axis=1)
arr_expanded.shape

(4, 1)